freebsd_instance:
  image_family: freebsd-12-0

task:
  env:
    matrix:
      - INSTANCE: freebsd-12.0
  install_script: pkg install -y ruby
  bundle_install_script: bundle install
  verify_script:
    bin/kitchen verify ${INSTANCE}
