freebsd_instance:
  image_family: freebsd-12-0

task:
  env:
    matrix:
      - INSTANCE: freebsd-12.0
  intall_script: pkg install -y ruby

  bundle_install_script: gem install bundler && bundle install
  verify_script:
    bin/kitchen verify ${INSTANCE}
